#include <iostream>
#include <cstdlib>
#include <ctime>
using namespace std;
int main() { 
    srand(time(0)); 
    int RandomNumber, GuessedNumber = -1;
    RandomNumber= rand();
  
    //For testing purpose:
    cout<<"Answer: "<<RandomNumber<<endl;
  
    while (GuessedNumber!=RandomNumber) {
        cout<<"__________________"<<endl;
	    cout<<"Guess the number generated by random number generator! "<<endl;
        cin>>GuessedNumber;
	    if(GuessedNumber>RandomNumber){
		    cout<<"Entered Value is greater than the Random Value generated by Random Value Generator."<<endl;
	    }
		else if(GuessedNumber < RandomNumber){
			cout<<"Entered Value is lesser than the Random Value generated by Random Value Generator."<<endl;
		}
	}
	
	cout<<"You guessed it."<<endl;
    return 0;

}
